#ifndef _ASUS_RC_H
#define _ASUS_RC_H

enum {
	APPS_AUTORUN_INITIALIZING=0,
	APPS_AUTORUN_CHECKING_DISK,
	APPS_AUTORUN_CREATING_SWAP,
	APPS_AUTORUN_EXECUTING,
	APPS_AUTORUN_FINISHED
};

enum {
	APPS_INSTALL_INITIALIZING=0,
	APPS_INSTALL_CHECKING_PARTITION,
	APPS_INSTALL_CHECKING_SWAP,
	APPS_INSTALL_DOWNLOADING,
	APPS_INSTALL_INSTALLING,
	APPS_INSTALL_FINISHED
};

enum {
	APPS_REMOVE_INITIALIZING=0,
	APPS_REMOVE_REMOVING,
	APPS_REMOVE_FINISHED
};

enum {
	APPS_SWITCH_INITIALIZING=0,
	APPS_SWITCH_STOPPING_APPS,
	APPS_SWITCH_STOPPING_SWAP,
	APPS_SWITCH_CHECKING_PARTITION,
	APPS_SWITCH_EXECUTING,
	APPS_SWITCH_FINISHED
};

enum {
	APPS_STOP_INITIALIZING=0,
	APPS_STOP_STOPPING,
	APPS_STOP_REMOVING_SWAP,
	APPS_STOP_FINISHED
};

enum {
	APPS_ENABLE_INITIALIZING=0,
	APPS_ENABLE_SETTING,
	APPS_ENABLE_FINISHED
};

enum {
	APPS_UPDATE_INITIALIZING=0,
	APPS_UPDATE_UPDATING,
	APPS_UPDATE_FINISHED
};

enum {
	APPS_UPGRADE_INITIALIZING=0,
	APPS_UPGRADE_DOWNLOADING,
	APPS_UPGRADE_REMOVING,
	APPS_UPGRADE_INSTALLING,
	APPS_UPGRADE_FINISHED
};

enum {
	APPS_ERROR_NO=0,
	APPS_ERROR_INPUT,
	APPS_ERROR_MOUNT,
	APPS_ERROR_POOLSIZE,
	APPS_ERROR_BASEAPPS,
	APPS_ERROR_NET,
	APPS_ERROR_SERVER,
	APPS_ERROR_FILE,
	APPS_ERROR_NONINSTALL,
	APPS_ERROR_REMOVE,
	APPS_ERROR_DISKIO
};

#endif
